[workspace]
resolver = "2"
members = [
    "toolchain/rust/crates/may_bootstrap",
    "toolchain/rust/crates/may_ast",
    "toolchain/rust/crates/may_lexer",
    "toolchain/rust/crates/may_parser",
    "toolchain/rust/crates/may_check",
    "toolchain/rust/crates/may_native",
    "toolchain/rust/crates/may_cli",
    "toolchain/rust/crates/may_lsp",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Maylang Contributors"]
repository = "https://github.com/mirged/maylang"

[profile.release]
opt-level = 3
lto = true

[workspace.dependencies]
may_ast = { path = "toolchain/rust/crates/may_ast" }
may_lexer = { path = "toolchain/rust/crates/may_lexer" }
may_parser = { path = "toolchain/rust/crates/may_parser" }
may_check = { path = "toolchain/rust/crates/may_check" }
may_native = { path = "toolchain/rust/crates/may_native" }
