#!/usr/bin/env python3
"""Generate compiled editor docs and the readable reference from one catalog."""
import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def render(entry):
    text = entry["summary"]
    if entry.get("parameters"):
        text += "\n\n**Parameters**\n" + "\n".join(
            f"- `{p['name']}`: {p['description']}" for p in entry["parameters"])
    if entry.get("returns"):
        text += "\n\n**Returns:** " + entry["returns"]
    if entry.get("notes"):
        text += "\n\n" + entry["notes"]
    text += "\n\n**Example**\n```may\n" + entry["example"] + "\n```"
    return text


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    catalog = json.loads((HERE / "reference.json").read_text())
    entries = {}
    chapters = ["# Maylang editor reference\n\n"
                "Generated from `reference.json`; edit the catalog and run "
                "`python3 docs/generate.py` from `toolchain/maylsp`. "
                "These descriptions also appear in hover, completion, and signature help. "
                "Signatures describe the public API; dynamic values may have several types.\n"]
    for group, values in catalog.items():
        chapters.append("\n## " + group + "\n")
        for name, entry in values.items():
            assert name not in entries, name
            assert entry["summary"] and entry["example"] and entry["signature"], name
            prose = render(entry)
            entries[name] = {"signature": entry["signature"], "docs": prose,
                             "params": [p["name"] for p in entry.get("parameters", [])],
                             "parameterDocs": {p["name"]: p["description"] for p in entry.get("parameters", [])}}
            chapters.append(f"\n### `{name}`\n\n```may\n{entry['signature']}\n```\n\n{prose}\n")
    source = "// Generated by docs/generate.py from docs/reference.json.\nlet LS_REFERENCE: Any = "
    source += json.dumps(entries, ensure_ascii=False, indent=4) + ";\n"
    outputs = {HERE.parent / "src/docs.may": source, HERE / "REFERENCE.md": "".join(chapters)}
    for path, contents in outputs.items():
        if args.check:
            assert path.read_text() == contents, f"Regenerate {path}"
        else:
            path.write_text(contents)
    print(f"{'Checked' if args.check else 'Generated'} {len(entries)} documentation entries")


if __name__ == "__main__":
    main()
