#!/usr/bin/env python3
"""Embed native/dom_bridge.js into src/js_prelude.may.

Maylang string literals are single-line and decode a small set of escapes
(\\n, \\t, \\r, \\0, and \\<char> -> <char>), so the JavaScript source is
emitted as one escaped literal.  Re-run this after editing dom_bridge.js.
"""
import os
import sys
from pathlib import Path

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "native", "dom_bridge.js")
OUT = os.path.join(ROOT, "src", "js_prelude.may")


def escape(text: str) -> str:
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\0":
            out.append("\\0")
        elif ch == "$":
            out.append("\\$")
        else:
            out.append(ch)
    return "".join(out)


def main() -> int:
    with open(SRC, "r", encoding="utf-8") as fh:
        js = fh.read()
    body = escape(js)
    generated = ("// Generated by tools/embed_js.py from native/dom_bridge.js.\n"
                 "// Do not edit by hand; run `make embed` to regenerate.\n\n"
                 "fun js_prelude() -> Str {\n" + '    return "' + body + '";\n' + "}\n")
    current = Path(OUT).read_text(encoding="utf-8") if Path(OUT).exists() else ""
    if "--check" in sys.argv:
        if current != generated:
            print("stale JavaScript bridge: run make embed", file=sys.stderr)
            return 1
        return 0
    if current == generated:
        # Keep the dependency timestamp current without rewriting its bytes.
        Path(OUT).touch()
        return 0
    Path(OUT).write_text(generated, encoding="utf-8")
    print("wrote", OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
