export const groups = [
  { title: 'Get started', items: [
    ['overview', 'Maylang overview'], ['installation', 'Install and compile'], ['first-program', 'Your first program'], ['project-layout', 'Programs and modules']
  ] },
  { title: 'Language reference', items: [
    ['lexical', 'Lexical structure'], ['types', 'Types and values'], ['variables', 'Variables and constants'], ['expressions', 'Expressions and operators'], ['functions', 'Functions'], ['closures', 'Closures and lambdas'], ['control-flow', 'Control flow'], ['pattern-matching', 'Pattern matching'], ['collections', 'Collections'], ['strings', 'Strings and interpolation'], ['records', 'Structs and enums'], ['errors', 'Errors and safe operations'], ['modules', 'Modules and visibility'], ['generics', 'Generics and type checking']
  ] },
  { title: 'Library and runtime', items: [
    ['builtins', 'Built-in functions'], ['standard-library', 'Standard library'], ['io-json', 'Files and JSON'], ['fibers', 'Fibers and scheduling'], ['native', 'Native compilation'], ['memory', 'Memory and garbage collection'], ['ffi', 'Pointers and foreign calls'], ['html-css', 'Generating HTML and CSS']
  ] },
  { title: 'Appendix', items: [ ['migration', 'Legacy syntax and migration'], ['limitations', 'Current limitations'], ['glossary', 'Glossary and further reading'] ] }
];

export const docs = {
  overview: { title:'Maylang overview', intro:'Maylang is a statically checked, expression-oriented language with a compact syntax and a compiler that emits freestanding x86-64 executables.', sections:[
    ['A language for small native programs', `Maylang combines familiar structured programming with closures, collections, pattern matching, safe speculative execution, and a small native runtime. The self-hosted compiler, mayc, is written in Maylang. New programs should target its strict syntax: explicit annotations, explicit return statements, and compile-time checking.`, `Maylang source → module expansion → strict type checking → native code → executable`],
    ['Two compiler surfaces', `The repository contains a newer self-hosted compiler (toolchain/mayc/mayc_new) and a historical Rust implementation. They overlap but are not identical. The strict compiler is the current authoring target. Historical grammar and examples may show untyped declarations or expression-bodied functions; those examples need migration before strict compilation.`],
    ['What the language is good at', `Maylang supports command-line tools, data processing, simulations, developer tools, and native programs that need direct OS access. Its standard library includes algorithms, collections, statistics, CSV, JSON, file helpers, and machine-learning modules. It can also generate text artifacts such as HTML, CSS, and configuration files.`],
    ['A small example', `This example shows the strict function and binding syntax used throughout the reference.`, `fun twice(value: Int) -> Int {\n    return value * 2;\n}\n\nlet answer: Int = twice(21);\nprint(answer); // 42`]
  ], see:['first-program','types','native'] },
  installation: { title:'Install and compile', intro:'Build Maylang programs with the self-hosted compiler included in this repository.', sections:[
    ['Compile from the repository', `Run commands from the repository root. The self-hosted compiler reads Maylang source, checks it, and writes a native executable.`, `toolchain/mayc/mayc_new examples/strict.may -o /tmp/strict-example\n/tmp/strict-example`],
    ['Compiler sidecars and libraries', `The compiler expects runtime.may, native.may, and prelude.may to be available. In the repository checkout it discovers those files relative to the compiler or repository layout. The prelude loads by default; MAYLANG_NO_PRELUDE=1 turns it off. Standard-library module lookup checks the importing source directory and configured stdlib locations.`],
    ['Compile your own file', `Create a file such as hello.may, then pass its path to mayc and choose an output path with -o. The generated file is an executable; run it directly. Use --legacy only when compiling old, untyped source that has not yet been migrated.`, `toolchain/mayc/mayc_new hello.may -o hello\n./hello\n\n# Legacy source only\ntoolchain/mayc/mayc_new --legacy old_program.may -o old_program`],
    ['Editor support', `The repository includes a VS Code extension and a Maylang language server. See editors/vscode/README.md and docs/LSP.md for setup and settings. Strict checking is enabled by default.`]
  ], see:['first-program','migration','modules'] },
  'first-program': { title:'Your first program', intro:'A strict Maylang program uses typed bindings, typed function signatures, and explicit returns.', sections:[
    ['Write a function', `A function begins with fun, lists typed parameters, and declares its result after ->. A function body is a block. In strict mode, every path must return a value of the declared type (or use return; for Nil).`, `fun greet(name: Str) -> Str {\n    return "Hello, \${name}!";\n}\n\nprint(greet("Ada"));`],
    ['Add a mutable value', `let declares an immutable binding. mut declares a binding that may be assigned again. Initializers are checked against the declared type.`, `let limit: Int = 10;\nmut current: Int = 0;\nwhile current < limit {\n    current += 1;\n}\nprint(current);`],
    ['Compile and run', `Save the program as hello.may and compile it from the repository root.`, `toolchain/mayc/mayc_new hello.may -o /tmp/hello\n/tmp/hello`],
    ['Read the next topics', `Continue with types and values, expressions, functions, and control flow. The examples throughout this reference use strict syntax unless clearly marked as historical.`]
  ], see:['types','variables','functions','control-flow'] },
  'project-layout': { title:'Programs and modules', intro:'A Maylang application starts from one source file and can import other source files and standard-library modules.', sections:[
    ['Entry source', `Pass the application entry file to mayc. Imports are resolved while compiling and expanded into the program; there is no runtime module loader.`, `toolchain/mayc/mayc_new src/main.may -o build/app`],
    ['Split code into modules', `Keep related declarations in their own files. Use an alias for a module import when you want qualified access and to avoid ambiguous names.`, `// geometry.may\npub fun square(n: Int) -> Int { return n * n; }\n\n// main.may\nimport "geometry.may" as geometry;\nlet area: Int = geometry.square(5);`],
    ['Project conventions', `Use .may for source files, group application code under src/, and keep reusable modules small. The example_projects/ directory groups complete Maylang applications by type and demonstrates real module boundaries.`]
  ], see:['modules','standard-library','installation'] },
  lexical: { title:'Lexical structure', intro:'Maylang source consists of declarations and statements built from identifiers, literals, operators, and comments.', sections:[
    ['Comments', `Line comments begin with //. Block comments use /* and */ and may nest. Comments are ignored by the compiler except as separators.`, `// A line comment\n/* Outer comment\n   /* nested comment */\n*/`],
    ['Identifiers and keywords', `Identifiers name bindings, functions, types, fields, and modules. The language reserves words such as fun, let, mut, return, if, else, while, for, in, break, continue, struct, enum, match, may, otherwise, unless, import, from, as, pub, and true/false/nil.`],
    ['Literals', `Integer and floating-point numeric literals, strings, booleans, and nil are built into the language. Strings are double quoted and support escapes and interpolation. Lists use square brackets; maps use braces with key/value pairs.`, `let text: Str = "line one\\nline two";\nlet enabled: Bool = true;\nlet nothing: Any = nil;\nlet numbers: List<Int> = [1, 2, 3];\nlet settings: Map<Str, Int> = {"port": 8080};`],
    ['Statement endings and blocks', `Declarations and expression statements end with semicolons. Braces delimit blocks, function bodies, map literals, struct and enum declarations, and match arms. Put map literals in expression positions where braces are not ambiguous with a statement block.`]
  ], see:['expressions','types'] },
  types: { title:'Types and values', intro:'Strict Maylang checks types before code generation. Types make function and data contracts explicit while runtime values keep a dynamic tagged representation.', sections:[
    ['Primitive types', `The core types are Int, Float, Bool, Str, and Nil. The compiler also accepts fixed-width integer and float names, but these annotations currently map to the regular tagged Int and Float runtime values; they do not select storage widths or guarantee range checks.`, `let attempts: Int = 3;\nlet ratio: Float = 0.75;\nlet ready: Bool = false;\nlet label: Str = "worker";`],
    ['Collection and compound types', `Write generic collection types with arguments: List<T>, Slice<T>, Map<K,V>, Option<T>, Result<T,E>, and Tuple<T,...>. Fixed-size arrays use [T; N]. Function types use (A, B) -> R or Fn(A, B) -> R. Bare generic collection names are not valid annotations.`, `let names: List<Str> = ["Ada", "Linus"];\nlet counts: Map<Str, Int> = {"ready": 2};\nlet maybe_id: Option<Int> = nil;\nlet transform: (Int) -> Int = fun(x: Int) -> Int { return x + 1; };`],
    ['Optional map lookup', `Indexing a map may miss, so its type is Optional<V>. Coalesce to provide a value, or use a may boundary when a larger computation may fail.`, `let counts: Map<Str, Int> = {"apple": 2};\nlet pears: Int = counts["pear"] ?? 0;`],
    ['Any and gradual boundaries', `Any opts a value out of static checking. It is useful for heterogeneous parsed data, runtime maps, ASTs, raw APIs, and migrated legacy code. Values are still checked dynamically by runtime operations where necessary; Any does not make an invalid operation safe.`],
    ['Type erasure and runtime representation', `The checker verifies declarations, calls, assignments, struct fields, collection elements, and return values. Type annotations are erased for execution. Integers, floats, strings, lists, maps, and closures use the runtime's tagged value model. Integers currently have a 61-bit immediate range; overflow raises a catchable arithmetic fault.`]
  ], see:['generics','variables','errors'] },
  variables: { title:'Variables and constants', intro:'Bindings declare named values. Use let for a value that never changes and mut for state that changes over time.', sections:[
    ['Immutable let bindings', `A let binding is initialized once and cannot be reassigned. Mayc infers its type from the initializer; add an annotation when you want to state the contract explicitly.`, `let greeting: Str = "hello";\nlet count: Int = 4;`],
    ['Mutable bindings', `mut declares a mutable local. Compound assignment operators update an existing mutable value.`, `mut retries: Int = 0;\nretries += 1;\nretries *= 2;`],
    ['Scope and shadowing', `Bindings live in their lexical block. Nested blocks can read outer bindings and declare their own locals. The strict checker detects assignment to an immutable binding and use of names outside their scope.`],
    ['Destructuring', `The historical language and parser include record and list destructuring. In strict mayc, destructuring declarations and loop patterns currently need to be expanded into individually typed bindings.`, `// Expand destructuring into typed local bindings in strict code.\nlet point: Point = Point(3, 4);\nlet x: Int = point.x;\nlet y: Int = point.y;`]
  ], see:['types','expressions','limitations'] },
  expressions: { title:'Expressions and operators', intro:'Expressions compute values. Blocks, if, match, and may can all provide values to surrounding expressions.', sections:[
    ['Arithmetic', `Arithmetic operators include addition, subtraction, multiplication, division, remainder, and exponentiation. Integer overflow and division by zero may raise catchable faults.`, `let power: Int = 2 ** 10;\nlet remainder: Int = 17 % 5;\nlet ratio: Float = 7.0 / 2.0;`],
    ['Comparison and logic', `Comparisons include ==, !=, <, <=, >, and >=. Boolean operators and/or short-circuit. Conditions in strict code must have type Bool.`, `if count > 0 and ready {\n    print("ready");\n}`],
    ['Assignment operators', `Use = for assignment to a mutable binding and +=, -=, *=, /= for arithmetic update. Reassignments must preserve the binding's checked type.`, `mut total: Int = 10;\ntotal += 4;`],
    ['Pipeline operator', `The pipeline operator is part of the historical language tour and Rust implementation. Verify support in the current mayc compiler before using it in strict source. The equivalent explicit calls are portable:`, `let selected: List<Int> = filter(values, is_even);\nlet doubled: List<Int> = map(selected, double);\nlet total: Int = sum(doubled);`],
    ['Operator precedence', `Multiplication binds more tightly than addition; comparisons bind less tightly than arithmetic; boolean operators combine conditions. Use parentheses when grouping matters or clarity improves.`]
  ], see:['control-flow','functions','limitations'] },
  functions: { title:'Functions', intro:'Functions name reusable computations and establish typed parameter and result contracts.', sections:[
    ['Declaration syntax', `Declare a function with fun, typed parameters, and a block. The result type may be explicit or inferred from returns. Strict functions use explicit return statements.`, `fun add(left: Int, right: Int) -> Int {\n    return left + right;\n}\n\nlet answer: Int = add(20, 22);`],
    ['Return paths', `Every path in a strict function must return a value compatible with the result type. Use return; in a function returning Nil. The checker is conservative about loops, so place a return after a loop even if you expect it never to finish.`, `fun abs_value(n: Int) -> Int {\n    if n < 0 { return 0 - n; }\n    return n;\n}\n\nfun log_message(message: Str) -> Nil {\n    print(message);\n    return;\n}`],
    ['Parameters and calls', `The compiler checks argument count and argument types at each statically known call. Generic functions can accept related types through type parameters. Dynamic values typed Any can defer some checks until runtime.`],
    ['Recursion and tail calls', `Recursive functions can call themselves. The compiler optimizes self tail calls to use constant stack space.`, `fun factorial(n: Int) -> Int {\n    if n <= 1 { return 1; }\n    return n * factorial(n - 1);\n}`],
    ['Anonymous functions', `Anonymous functions can be assigned to typed function values and passed to higher-order functions. The strict compiler requires parameter annotations, a return type, and explicit returns.`, `let triple: (Int) -> Int = fun(n: Int) -> Int {\n    return n * 3;\n};`]
  ], see:['closures','generics','control-flow'] },
  closures: { title:'Closures and lambdas', intro:'A closure is a function value that can retain access to bindings in the scope where it was created.', sections:[
    ['Capture a value', `A nested function may refer to a surrounding binding. Captured mutable bindings are shared with the closure, allowing stateful functions such as counters.`, `fun make_counter(start: Int) -> () -> Int {\n    mut current: Int = start;\n    fun next() -> Int {\n        current += 1;\n        return current;\n    }\n    return next;\n}\n\nlet next_id: () -> Int = make_counter(100);\nprint(next_id()); // 101`],
    ['Function values', `Function types describe parameter types and results. Use them to document callback contracts. Higher-order functions such as map, filter, and reduce consume function values.`, `let is_positive: (Int) -> Bool = fun(n: Int) -> Bool {\n    return n > 0;\n};`],
    ['Capture semantics', `Closures capture variables through shared cells in the native runtime. Multiple closures that capture the same mutable binding observe its updates. The garbage collector traces closures and their captured cells.`],
    ['Syntax notes', `Short lambda forms such as |x| expression and x => expression appear in historical syntax documentation. The strict compiler's examples should use fully annotated fun expressions until short-lambda support is confirmed for the exact compiler build.`]
  ], see:['functions','memory','standard-library'] },
  'control-flow': { title:'Control flow', intro:'Use conditional expressions, loops, early exits, and guards to select and repeat work.', sections:[
    ['if and else', `Conditions must be Bool in strict code. An if expression may return a value from either branch; statement form is also available.`, `let label: Str = if score >= 50 { "pass" } else { "retry" };`],
    ['while loops', `A while loop checks its condition before each iteration. break exits the nearest loop; continue begins the next iteration.`, `mut i: Int = 0;\nwhile i < 3 {\n    print(i);\n    i += 1;\n}`],
    ['for loops and ranges', `A for loop iterates over a range or collection. The loop binding needs a type annotation in strict source. Ranges support exclusive .. and inclusive ..= endpoints; ascending and descending ranges are supported by the native implementation.`, `let values: List<Int> = [2, 4, 6];\nfor value: Int in values {\n    print(value);\n}\nfor number: Int in 1..=3 { print(number); }`],
    ['unless guards', `unless is an inverted condition useful for early guards. If the condition is false, the body runs. Parentheses around the condition are accepted.`, `fun first(values: List<Int>) -> Int {\n    unless (len(values) > 0) { return 0; }\n    return values[0];\n}`],
    ['Comprehensions', `List comprehensions transform an iterable and may filter its values. Bind the element with an explicit type.`, `let squares: List<Int> = [n * n for n: Int in 1..=5 if n % 2 == 1];`]
  ], see:['pattern-matching','expressions','collections'] },
  'pattern-matching': { title:'Pattern matching', intro:'match selects the first arm whose pattern matches. It is an expression and can produce a value.', sections:[
    ['Literal and wildcard patterns', `Patterns include supported literals, an identifier that binds the matched value, and the wildcard _. Arms use => and are separated by commas.`, `let code: Int = 404;\nlet message: Str = match (code) {\n    200 => "OK",\n    404 => "Not found",\n    _ => "Unknown",\n};`],
    ['Bindings and guards', `A name pattern binds the subject for use in its arm. Add if and a boolean expression for a guarded arm. The first matching arm wins.`, `let category: Str = match (size) {\n    n if n < 0 => "invalid",\n    n if n < 10 => "small",\n    _ => "large",\n};`],
    ['Non-exhaustive matches', `A match with no matching arm raises a match fault. Strict mayc checks that Bool matches cover both true and false, unless an unguarded name or wildcard arm covers all values. For other input types, use a final wildcard arm. Enum variant destructuring is not generally supported by the strict matcher.`],
    ['Enums and tags', `Enum constructors produce tagged values. The historical pattern-matching examples inspect a tag field and match its string name.`, `enum State { Ready, Stopped }\nlet state: State = State.Ready;\nlet label: Str = match (state.tag) {\n    "Ready" => "running",\n    _ => "stopped",\n};`]
  ], see:['records','errors','control-flow'] },
  collections: { title:'Collections', intro:'Lists and maps are the core collection values. Their element contracts are checked when concrete generic types are used.', sections:[
    ['Lists', `A list literal uses brackets. Indexing starts at zero. Use push to append, pop to remove the last element, len to get the number of entries, and for to iterate.`, `mut numbers: List<Int> = [2, 3];\npush(numbers, 5);\nlet first: Int = numbers[0];\nlet size: Int = len(numbers);`],
    ['Maps', `A map literal contains key/value pairs. Use dot access for identifier-shaped string keys or bracket access for general keys. Map iteration yields keys.`, `let names: Map<Str, Int> = {"Ada": 1, "Lin": 2};\nlet ada: Int = names["Ada"] ?? 0;\nlet keys_list: List<Str> = keys(names);`],
    ['Spread and merge', `List spread inserts the elements of another list. Map spread copies entries into a new map; later entries replace earlier values for the same key.`, `let rest: List<Int> = [3, 4];\nlet values: List<Int> = [1, 2, ...rest];\nlet base: Map<Str, Int> = {"port": 80};\nlet local: Map<Str, Int> = {...base, "port": 8080};`],
    ['Higher-order operations', `The runtime includes map, filter, reduce, any, all, sort, reverse, sum, product, count, find, slice, enumerate, zip, flatten, and unique. The standard library adds richer algorithms and iterators.`, `let values: List<Int> = [1, 2, 3, 4];\nlet total: Int = reduce(values, fun(acc: Int, n: Int) -> Int { return acc + n; }, 0);\nlet has_large: Bool = any(values, fun(n: Int) -> Bool { return n > 3; });`],
    ['Comprehensions', `Comprehensions build a new list by evaluating an expression for each input item, optionally filtering first.`, `let even_doubles: List<Int> = [n * 2 for n: Int in 1..=8 if n % 2 == 0];`]
  ], see:['types','strings','standard-library'] },
  strings: { title:'Strings and interpolation', intro:'Strings are UTF-8 values with interpolation and common transformation helpers.', sections:[
    ['String literals and escapes', `String literals are double quoted. Common backslash escapes represent quotes, backslashes, and control characters. UTF-8 code points are supported by length, indexing, and chars.`, `let text: Str = "Maylang\\nNative";\nlet symbol: Str = "λ";\nprint(text);`],
    ['Interpolation', `Embed an expression in a string with ${'${...}'}. Use it to format names, numbers, and results.`, `let name: Str = "Ada";\nlet count: Int = 3;\nprint("${'${name}'} has ${'${count}'} tasks");`],
    ['String methods', `Common methods include trim, split, to_upper, to_lower, contains, starts_with, ends_with, replace, index_of, and chars.`, `let raw: Str = "  red,green,blue  ";\nlet parts: List<Str> = raw.trim().split(",");\nlet title: Str = parts[0].to_upper();`],
    ['Formatting values', `Use str to convert a value to a string and join to combine a list of strings. The format module adds tables, key/value blocks, durations, byte sizes, percentages, and ANSI styles.`, `let label: Str = "count=" + str(42);\nlet line: Str = join(["May", "lang"], "");`],
    ['Unicode limits', `String indexing, len, and chars operate on UTF-8 code points rather than grapheme clusters. A displayed glyph made from multiple code points may count as more than one character.`]
  ], see:['collections','standard-library','html-css'] },
  records: { title:'Structs and enums', intro:'Structs model named fields; enums model a finite set of named variants.', sections:[
    ['Struct declarations', `Every strict struct field has a type. The generated constructor takes field values in declaration order and returns the named struct type.`, `struct Point { x: Int, y: Int }\nlet origin: Point = Point(0, 0);\nprint(origin.x, origin.y);`],
    ['Enums and payloads', `An enum declares variants. Variant payload parameters may be named or positional depending on the declaration syntax supported by the compiler. Constructors are type checked.`, `enum Event { Started, Exit(code: Int) }\nlet event: Event = Event.Exit(0);`],
    ['Field access and runtime model', `The checker validates known fields on nominal struct types. Runtime values use tagged maps/records; types do not introduce separate machine layouts. Maps and structs therefore share parts of the runtime representation.`],
    ['Operator members', `Historical Maylang documentation describes fixed struct members that overload +, -, *, and / by calling a method on the left operand. Strict static contracts for overloaded arithmetic are not yet supported; dynamic Any boundaries are required for those legacy use cases.`],
    ['No inheritance', `The language does not currently provide class inheritance or interface/trait conformance checking. Prefer composing records and passing functions explicitly.`]
  ], see:['types','pattern-matching','limitations'] },
  errors: { title:'Errors and safe operations', intro:'Maylang offers catchable runtime faults and safe access operators to handle uncertain operations locally.', sections:[
    ['The may boundary', `A may block catches a runtime fault raised within the block. With otherwise, execution continues in the handler. A bare may evaluates to nil when it catches a fault.`, `let port: Any = may { parse_int(input("Port: ")) } otherwise {\n    print("Invalid input: \${err.message}");\n    8080\n};`],
    ['Structured errors', `Inside otherwise, err exposes message, kind, and stack fields. Error kinds include categories such as arithmetic, io, type, match, and explicit failure.`, `let message: Str = may { fail("configuration unavailable") } otherwise {\n    "\${err.kind}: \${err.message}"\n};`],
    ['Nil coalescing and safe navigation', `The ?? operator yields its left operand when it is not nil and otherwise evaluates the fallback. Safe navigation ?. short-circuits a property or call chain when a receiver is nil.`, `let port: Int = (may { parse_int(raw_port) }) ?? 8080;\nlet email: Any = user?.profile?.email;`],
    ['Results and options', `Option and Result are recognized by the type checker as type forms. The stdlib result module offers constructors and helpers such as ok, error, unwrap_or, map_result, and and_then. The legacy postfix ? propagation syntax is not part of the strict compiler surface.`],
    ['Handle faults at boundaries', `Use may around operations that are expected to fail, then convert the failure into a useful local default or diagnostic. Avoid swallowing faults when the caller needs to know that work did not succeed.`]
  ], see:['types','io-json','standard-library'] },
  modules: { title:'Modules and visibility', intro:'Imports compose source files at compile time and give module declarations separate namespaces.', sections:[
    ['Import a module', `An alias import keeps module members qualified. A plain import exposes module names unqualified as well as through its module namespace; importing duplicate unqualified names is an error.`, `import "math_tools.may" as math_tools;\nlet result: Int = math_tools.square(9);`],
    ['Select names', `Use from ... import to bring selected names into the current module scope.`, `from "math_tools.may" import square, clamp;\nlet result: Int = square(5);`],
    ['Visibility with pub', `If a module marks any top-level declaration pub, only pub declarations are exported; other names remain private. A module without any pub declarations exports all top-level names for compatibility.`, `pub fun square(value: Int) -> Int { return value * value; }\n\nfun internal_helper() -> Int { return 2; }`],
    ['Resolution and namespaces', `Imports are resolved and inlined at build time. Top-level declarations receive module-qualified identities so same-named private functions in different files do not collide. Resolution checks the importing directory, MAYLANG_STDLIB, ./stdlib, locations near the executable, and ~/.maylang/stdlib.`],
    ['The prelude', `stdlib/prelude.may loads automatically and contains small common helpers. Set MAYLANG_NO_PRELUDE=1 to disable automatic prelude loading.`]
  ], see:['project-layout','standard-library','installation'] },
  generics: { title:'Generics and type checking', intro:'Generic type parameters let a function express relationships between its input and output types.', sections:[
    ['Generic functions', `Declare type parameters after a function name. The checker unifies parameter and argument types at a call site.`, `fun identity<T>(value: T) -> T {\n    return value;\n}\n\nlet id: Int = identity(42);\nlet name: Str = identity("Ada");`],
    ['Generic collection types', `List<T>, Map<K,V>, Option<T>, Result<T,E>, and function types express structure in APIs. Constructors and calls are checked against their declared types.`, `fun first<T>(items: List<T>) -> T {\n    return items[0];\n}`],
    ['Checker guarantees', `Strict checking catches invalid rebinding, scope errors, invalid arithmetic, non-callable values, wrong argument counts, annotation mismatches, invalid collection contents, invalid struct fields, and return type mismatches. It reports unknown or dynamic information as Any rather than pretending to prove more than it can.`],
    ['Dynamic escape hatches', `Use Any at boundaries that cannot yet be represented with static types, such as decoded JSON, dynamic property names, runtime generated values, and low-level pointer operations. Replace Any with concrete types when a stable contract becomes known.`],
    ['Types are erased', `The strict type system is a compile-time checker. Types do not currently select machine-width integers, create runtime generic specializations, or guarantee that dynamically typed Any operations cannot fail.`]
  ], see:['types','variables','limitations'] },
  builtins: { title:'Built-in functions', intro:'Built-ins are operations supplied by the runtime and native prelude. Higher-level APIs are implemented in the standard library.', sections:[
    ['Values and collections', `Core helpers include print, str, int, float, bool, type, len, push, pop, range, keys, values, has, merge, remove, get, and assert.`, `let items: List<Int> = range(1, 5);\npush(items, 5);\nprint(type(items), len(items), sum(items));`],
    ['Higher-order and numeric operations', `List helpers include map, filter, reduce, any, all, sort, reverse, sum, product, count, find, slice, enumerate, zip, flatten, and unique. Numeric primitives include abs, min, max, clamp, sqrt, floor, ceil, round, trunc, sign, pow, and trigonometric/transcendental functions.`],
    ['String operations', `String helpers include parse_int, parse_float, split, trim, to_upper, to_lower, contains, starts_with, ends_with, replace, index_of, and chars.`],
    ['Environment and process', `OS operations include input, args, env, exit, clock, time, read_file, write_file, file_exists, mkdir, read_dir, exec, wait, system, and sleep. Directory enumeration is Linux-only in the native backend.`],
    ['JSON and low-level primitives', `json_parse and json_stringify handle JSON values. Advanced runtime primitives expose fibers, pointers, raw loads/stores, syscalls, and C ABI calls; consult their dedicated reference pages.`]
  ], see:['standard-library','io-json','fibers','ffi'] },
  'standard-library': { title:'Standard library', intro:'Most reusable Maylang APIs live in source modules under stdlib/. Import the module or selected public declarations you need.', sections:[
    ['Module catalog', `math: gcd, lcm, primality, factorial, fibonacci, averages, geometry. string: capitalization, words, lines, CSV helpers, padding, truncation. collections: stack, queue, and set operations. algo: sorting, searching, zip, flatten, chunk, partition, group_by. iter: windows, scan, pairwise, take/drop while, cartesian products.`, `import "math.may";\nfrom "algo.may" import quick_sort, binary_search;\nlet sorted: List<Int> = quick_sort([9, 1, 4]);\nlet index: Int = binary_search(sorted, 4);`],
    ['More modules', `functional provides composition, curry, memoize, and partial application. stats provides descriptive statistics, quantiles, covariance, correlation, and regression. random provides seeded draws, normal samples, shuffle, and sampling. csv parses and renders quoted records. path performs lexical path operations. validate and format provide reusable data checks and report formatting. result and test provide result helpers and assertions.`],
    ['Machine learning', `stdlib/ml contains tensors, classical algorithms, dense neural networks, loss functions, optimizers, model serialization, and data helpers. Its scope and API are documented in stdlib/ml/README.md.`],
    ['Import examples', `Import resolution starts next to the importing file, then checks configured standard-library locations.`, `import "math.may";\nfrom "algo.may" import quick_sort;\nprint(gcd(48, 36));\nprint(quick_sort([3, 1, 2]));`],
    ['Explore library source', `The standard library is written in Maylang wherever possible. Reading a module is often the most direct way to learn its exact signatures and behavior. See stdlib/README.md for the catalog and search path.`]
  ], see:['modules','builtins','io-json'] },
  'io-json': { title:'Files and JSON', intro:'Native programs can read and write files, parse and produce JSON, inspect environment variables, and work with processes.', sections:[
    ['Read and write files', `read_file returns file contents as a string; write_file stores a string at the requested path. file_exists checks for an existing path. Failures raise io faults and can be handled with may.`, `let source: Str = read_file("input.txt");\nwrite_file("copy.txt", source);\nlet exists: Bool = file_exists("copy.txt");`],
    ['JSON values', `json_parse decodes a JSON string to Maylang values; json_stringify encodes supported values. Use Any for heterogeneous JSON documents and validate expected fields before relying on them.`, `let doc: Any = json_parse(read_file("config.json"));\nlet port: Int = doc.server.port ?? 8080;\nwrite_file("normalized.json", json_stringify(doc));`],
    ['Environment and time', `env reads an environment variable. args exposes process arguments. clock returns epoch seconds as Float; time returns milliseconds as Int.`, `let home: Any = env("HOME");\nlet started: Float = clock();\nprint(args());`],
    ['Directories and child processes', `mkdir creates a directory; read_dir enumerates names on Linux. system executes a shell command and returns an exit status. exec starts a process from an argument list; wait obtains its status. sleep takes milliseconds.`, `mkdir("output");\nfor name: Str in read_dir(".") { print(name); }\nlet status: Int = system("true");`],
    ['I/O portability', `read_dir currently uses Linux getdents64 and is unavailable in the macOS native build. Process and environment behavior depend on the target operating system. Handle I/O faults where recovery is appropriate.`]
  ], see:['errors','builtins','html-css'] },
  fibers: { title:'Fibers and scheduling', intro:'Maylang supports cooperative fibers for interleaving independent tasks on one thread.', sections:[
    ['Start a fiber', `spawn schedules a zero-argument function value. run drains ready fibers. Fibers share the heap and are cooperative: a running fiber keeps control until it returns or calls yield.`, `fun worker(id: Int) -> Nil {\n    print("worker", id);\n    return;\n}\nspawn(fun() -> Nil { worker(1); return; });\nrun();`],
    ['Yield control', `yield suspends the current fiber and gives the scheduler a chance to run another ready fiber. There is no preemption.`, `fun count(id: Int) -> Nil {\n    mut i: Int = 0;\n    while i < 3 {\n        print(id, i);\n        yield();\n        i += 1;\n    }\n    return;\n}`],
    ['Scheduler behavior', `The runtime uses a round-robin ready queue with a fixed fiber table and per-fiber stack. Each fiber begins with a 256 KiB stack. The garbage collector scans suspended fiber stacks for roots.`],
    ['Current limits', `Fibers are not OS threads. There are no channels, mailboxes, preemption, or built-in synchronization primitives. Use explicit yields to make progress fair.`]
  ], see:['memory','native','limitations'] },
  native: { title:'Native compilation', intro:'The self-hosted compiler emits freestanding x86-64 executables without an assembler, linker, libc, or bytecode interpreter.', sections:[
    ['Build pipeline', `mayc expands modules, checks types, resolves names, lowers to an intermediate representation, generates x86-64 code, and writes an ELF executable. The runtime and native prelude are incorporated into the generated program.`, `toolchain/mayc/mayc_new app.may -o app\n./app`],
    ['Targets and current status', `Linux x86-64 is the actively executed target. Mach-O output is generated for macOS but has not been executed from the development environment. An AArch64 scaffold emits a hello-world executable structure; the full compiler/runtime is not ported to AArch64.`],
    ['System calls and runtime', `The runtime uses OS system calls for output, process exit, memory reservation, and file/process operations. Values are tagged 64-bit words. Strings, lists, maps, and closures are heap objects.`],
    ['Executable inspection', `Generated ELF files contain code and data sections, symbols, and line mappings. The binary is statically self-contained; there is no dynamic linker dependency.`]
  ], see:['memory','ffi','limitations'] },
  memory: { title:'Memory and garbage collection', intro:'Maylang manages heap objects automatically with a conservative, non-moving mark-sweep collector.', sections:[
    ['Heap objects', `Strings, floats, arrays, lists, maps, closures, and captured cells are allocated in a demand-zero mmap heap. Each allocation carries a header that records size and object kind.`, `let values: List<Str> = ["one", "two", "three"];\nlet lengths: List<Int> = map(values, fun(s: Str) -> Int {\n    return len(s);\n});`],
    ['Tracing roots', `The collector scans registers, stack memory, data memory, and suspended fiber stacks for possible heap pointers. It traces known object fields precisely once an allocated object is found. The collector is conservative at roots, so stale pointer-like words may retain objects longer.`],
    ['Generations and allocation', `New objects are young. A minor collection promotes reachable young objects and reclaims unreachable young objects; major collection can reclaim old garbage. Free blocks are split and coalesced. The heap reservation is 1 GiB by default and does not grow beyond its configured reservation.`],
    ['Operational limitations', `Objects do not move, so references remain stable, but the collector cannot compact fragmentation. If live data exceeds the heap, the runtime exits with status 70. See docs/GC.md for object layout and the collector algorithm.`]
  ], see:['native','fibers','ffi'] },
  ffi: { title:'Pointers and foreign calls', intro:'Low-level built-ins expose raw memory and system interfaces for advanced native programs.', sections:[
    ['Addresses and pointer values', `A pointer is represented as an Int. addr returns a payload address for heap-backed values; immediates have no payload address. cstr creates a NUL-terminated string copy for C interfaces.`, `let text: Str = "hello";\nlet address: Int = addr(text);\nlet c_string: Int = cstr(text);`],
    ['Raw loads and stores', `load8, load16, load32, and load64 read untagged words. store8, store16, store32, and store64 write untagged values. The caller is responsible for valid addresses, alignment, object lifetime, and representation.`, `let pointer: Int = addr("A");\nlet byte: Int = load8(pointer);`],
    ['System calls', `syscall takes a system-call number followed by raw integer arguments and returns the raw result as a Maylang integer. Argument registers and system-call numbers are target-specific.`, `// Linux x86-64 write(1, "hi\\n", 3)\nsyscall(1, 1, addr("hi\\n"), 3);`],
    ['C ABI calls', `ccall(address, argv) calls a code address using the System V integer/pointer calling convention. extern_c wraps an address as a callable function value. Up to six integer or pointer arguments are supported; float and stack arguments are not wired up.`, `let result: Int = ccall(function_address, [40, 2]);`],
    ['Safety and portability', `Invalid raw addresses can crash or corrupt a process. These functions bypass most language-level safety and are target-specific. Dynamic linking named external symbols is not supported; calls use raw addresses.`]
  ], see:['native','memory','limitations'] },
  'html-css': { title:'Generating HTML and CSS', intro:'Maylang programs run natively, but they can generate web pages and stylesheets as text files.', sections:[
    ['Generate files', `Build HTML and CSS strings in a Maylang program and write them with write_file. The generated document can then be opened in a browser or served from a static web server.`, `let title: Str = "Maylang page";\nlet html: Str = "<!doctype html>\\n<html lang=\\"en\\">\\n<head>\\n<meta charset=\\"utf-8\\">\\n<title>${'${title}'}</title>\\n<link rel=\\"stylesheet\\" href=\\"site.css\\">\\n</head>\\n<body><main class=\\"card\\"><h1>${'${title}'}</h1></main></body>\\n</html>\\n";\nlet css: Str = "body { font: 1rem system-ui; background: #f4f6fb; }\\n.card { max-width: 40rem; margin: 4rem auto; padding: 2rem; background: white; border-radius: 1rem; }\\n";\nwrite_file("site/index.html", html);\nwrite_file("site/site.css", css);`],
    ['Escape interpolated values', `Maylang does not automatically HTML-escape interpolated strings. Escape untrusted text before inserting it into text or attribute contexts; validate URLs and other attribute values separately. Do not insert untrusted values into script or style content.`],
    ['Keep content and presentation separate', `Use a .may program to produce content and data, and keep substantial markup and stylesheet templates in separate source files when that is easier to maintain. Maylang does not provide browser DOM APIs or execute client-side JavaScript.`],
    ['Static site workflows', `A practical workflow is to compile a generator, run it to write a dist/ directory, then publish that directory with a static host. Use relative asset paths and keep output generation deterministic when possible.`]
  ], see:['io-json','strings','installation'] },
  migration: { title:'Legacy syntax and migration', intro:'Older Maylang examples use a more dynamic style. The self-hosted strict compiler requires explicit annotations and return statements.', sections:[
    ['Strict mode is the default', `Mayc infers local let/mut types and function result types. Parameters, struct fields, enum payloads, loop bindings, and comprehension bindings need annotations. Functions still require explicit return statements on every path. Conditions have type Bool.`, `// Legacy\nfun double(x) { x * 2 }\n\n// Strict\nfun double(x: Int) -> Int { return x * 2; }`],
    ['Use Any during migration', `Any lets existing dynamic code compile while preserving explicit migration boundaries. The migration script can add Any annotations and return statements as a starting point. Review its output and refine contracts afterward.`, `python3 toolchain/mayc/tools/migrate_strict.py old.may --write\ntoolchain/mayc/mayc_new old.may -o /tmp/old`],
    ['Legacy mode', `Pass --legacy to mayc only for source that still depends on untyped legacy syntax. The legacy Rust implementation is separate and does not define the current mayc surface.`],
    ['Migration checklist', `Annotate parameters, loop bindings, struct fields, and enum payloads; add binding or result annotations where they make contracts clearer; make every return explicit; add returns after loops where needed; type collection and callback values; split strict destructuring into typed locals; use Any only for dynamic boundaries; confirm parser support for historical operators and lambda forms.`]
  ], see:['types','functions','limitations'] },
  limitations: { title:'Current limitations', intro:'This page records important boundaries of the current self-hosted compiler and runtime so code examples do not imply unsupported guarantees.', sections:[
    ['Types and language features', `The runtime remains dynamically represented even when source is statically checked. Any bypasses static guarantees. Fixed-width annotations do not enforce fixed-width arithmetic. Strict destructuring is limited; match patterns are literals, names, and wildcard; generic user-defined constraints are limited; overloads and interface checking are not available.`],
    ['Runtime and platforms', `The full backend targets x86-64. AArch64 is a scaffold, and macOS output has not been runtime-validated in the development environment. read_dir is Linux-only. The heap reservation is fixed and cannot grow. Conservative roots may keep garbage alive; a live set larger than the heap terminates with an out-of-memory status.`],
    ['Concurrency and FFI', `Fibers are cooperative and single-threaded; they have no channels or preemption. C calls support up to six integer or pointer register arguments; float and stack arguments are not wired. There is no dynamic linking by symbol name.`],
    ['Source of truth', `Compiler implementation, docs/STRICT.md, toolchain/mayc/tests, and current examples provide the authoritative behavior for mayc. docs/GRAMMAR.md explicitly describes the legacy Rust toolchain, so it should not be read as a complete strict compiler specification.`]
  ], see:['native','memory','ffi','migration'] },
  glossary: { title:'Glossary and further reading', intro:'Short definitions for recurring Maylang terms, plus links to deeper repository references.', sections:[
    ['Glossary', `Any: dynamically checked boundary type. Closure: function value with captured bindings. Fiber: cooperative schedulable function with its own stack. Prelude: automatically loaded common helper module. Strict compiler: self-hosted mayc type-checking source by default. Tagged value: runtime word whose tag identifies the represented value kind.`, `let callback: (Int) -> Int = fun(n: Int) -> Int { return n + 1; };`],
    ['Language and compiler references', `Strict syntax and type rules: docs/STRICT.md. Legacy grammar and feature semantics: docs/GRAMMAR.md. Native backend: docs/NATIVE.md. Garbage collector: docs/GC.md. Language server: docs/LSP.md. Standard library catalog: stdlib/README.md. Compiler pipeline: toolchain/mayc/README.md.`],
    ['Examples to explore', `examples/strict.may demonstrates strict syntax. examples/features.may tours may, match, interpolation, spread, and comprehensions in annotated dynamic form. examples/modules/ shows imports. example_projects/apps/textstats and example_projects/games/starfall demonstrate larger applications.`]
  ], see:['overview','native','standard-library'] }
};
